ktor {
    deployment {
        port = 8080
        port = ${?PORT}
    }
    application {
        modules = [ com.campus.card.ApplicationKt.module ]
    }
}

database {
    url = ${?DATABASE_URL}
    url = "jdbc:h2:file:./data/campus_card;DB_CLOSE_DELAY=-1;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE"
    driver = ${?DATABASE_DRIVER}
    driver = "org.h2.Driver"
    user = ${?DATABASE_USER}
    user = "sa"
    password = ${?DATABASE_PASSWORD}
    password = ""
}

service {
    reissueFee = 20.00
    defaultPickupLocation = "卡务中心1号窗口"
}
